version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: feed_music_db
    environment:
      POSTGRES_USER: feedmusic
      POSTGRES_PASSWORD: feedmusic123
      POSTGRES_DB: feedmusic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedmusic"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: feed_music_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://feedmusic:feedmusic123@db:5432/feedmusic
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data: